In [1]:
using PyPlot, PyCall
np=pyimport("numpy")

PyObject <module 'numpy' from '/home/gridsan/aligho/.local/lib/python3.8/site-packages/numpy/__init__.py'>

In [4]:
readlines("../hBN_Optimization/hBN.lattice")

4-element Vector{String}:
 "lattice \\"
 "\t   4.727486978767153   -2.363743489383575    0.000000000000000  \\"
 "\t  -0.000000000000000    4.094123819672498    0.000000000000000  \\"
 "\t   0.000000000000000    0.000000000000000   40.000000000000000 #Note: latt-scale has been absorbed into these lattice vectors."

In [36]:
readlines("../hBN_Optimization/hBN.ionpos")

4-element Vector{String}:
 "# Ionic positions in lattice coordinates:"
 "ion B  -0.000000000000000   0.000000000000000   0.000000000000000 0"
 "ion N   0.333333333333333   0.666666666666667   0.000000000000000 0"
 ""

The commensuration angle is given by $cos^{-1}\Big(\frac{3q^2-p^2}{3q^2+p^2}\Big)$. For q=3, p=1, we get $\cos^{-1}(\frac{13}{14})$

In [55]:
function rot(θ::Real)
    rot_matrix =[cos(θ) -sin(θ); sin(θ) cos(θ) ]
    return rot_matrix
end
function rot_3x3(θ::Real)
    rot_matrix =[cos(θ) -sin(θ) 0; sin(θ) cos(θ) 0; 0 0 1 ]
    return rot_matrix
end

rot_3x3 (generic function with 1 method)

In [21]:
b=[-1/2, √3/2]

2-element Vector{Float64}:
 -0.5
  0.8660254037844386

In [30]:
θ = acos(13/14)

for (ii, jj, kk, ll) in Tuple.(CartesianIndices(rand(11, 11, 11, 11)))
    i = ii-6
    j = jj-6
    k = kk-6
    l = ll-6
    a=[1, 0]; b=[-1/2, √3/2]
    c=rot(θ)*a; d=rot(θ)*b
    diff = i*a+b*j-c*k-d*l
    isapprox(sum(diff.^2), 0, atol=1e-6) || continue
    println(i, " ", j, " ", k, " ", l)
end

1 -4 -1 -5
-4 -5 -5 -4
4 -2 2 -4
-1 -3 -2 -3
2 -1 1 -2
-3 -2 -3 -1
5 1 4 -1
0 0 0 0
-5 -1 -4 1
3 2 3 1
-2 1 -1 2
1 3 2 3
-4 2 -2 4
4 5 5 4
-1 4 1 5


In [31]:
#Below we define the matrices to take things from the superlattice basis to the layer bases

In [50]:
superlattice_to_layer1 = [-2 -1; 1 -3]
superlattice_to_layer1_3x3 = [-2 -1 0; 1 -3 0; 0 0 1]

superlattice_to_layer2 = [-1 -2; 2 -3]
superlattice_to_layer2_3x3 = [-1 -2 0; 2 -3 0; 0 0 1]

layer1_to_superlattice = inv(superlattice_to_layer1)
layer2_to_superlattice = inv(superlattice_to_layer2);

In [46]:
for i in -20:20
    for j in -20:20
        iprime, jprime = layer1_to_superlattice*[i, j]
        iprime >= 1 && continue
        jprime >= 1 && continue
        iprime < 0 && continue
        jprime < 0 && continue
        println("ion B $iprime $jprime 0 0" )
    end
end
println()
for i in -20:20
    for j in -20:20
        iprime, jprime = layer1_to_superlattice*[i+1/3, j+2/3]
        iprime >= 1 && continue
        jprime >= 1 && continue
        iprime < 0 && continue
        jprime < 0 && continue
        println("ion N $iprime $jprime 0 0" )
    end
end
println()
for i in -20:20
    for j in -20:20
        iprime, jprime = layer2_to_superlattice*[i, j]
        iprime >= 1 && continue
        jprime >= 1 && continue
        iprime < 0 && continue
        jprime < 0 && continue
        println("ion B $iprime $jprime \${d} 0" )
    end
end
println()
for i in -20:20
    for j in -20:20
        iprime, jprime = layer2_to_superlattice*[i+1/3, j+2/3]
        iprime >= 1 && continue
        jprime >= 1 && continue
        iprime < 0 && continue
        jprime < 0 && continue
        println("ion N $iprime $jprime \${d} 0" )
    end
end

ion B 0.5714285714285715 0.8571428571428571 0 0
ion B 0.7142857142857144 0.5714285714285714 0 0
ion B 0.8571428571428572 0.2857142857142857 0 0
ion B 0.1428571428571429 0.7142857142857142 0 0
ion B 0.28571428571428575 0.42857142857142855 0 0
ion B 0.4285714285714286 0.14285714285714285 0 0
ion B 0.0 0.0 0 0

ion N 0.9523809523809523 0.7619047619047619 0 0
ion N 0.3809523809523811 0.9047619047619048 0 0
ion N 0.523809523809524 0.6190476190476191 0 0
ion N 0.6666666666666667 0.3333333333333333 0 0
ion N 0.8095238095238096 0.04761904761904763 0 0
ion N 0.09523809523809526 0.4761904761904762 0 0
ion N 0.23809523809523814 0.1904761904761905 0 0

ion B 0.2857142857142857 0.8571428571428571 ${d} 0
ion B 0.5714285714285714 0.7142857142857142 ${d} 0
ion B 0.8571428571428571 0.5714285714285714 ${d} 0
ion B 0.14285714285714285 0.42857142857142855 ${d} 0
ion B 0.42857142857142855 0.2857142857142857 ${d} 0
ion B 0.7142857142857142 0.14285714285714285 ${d} 0
ion B 0.0 0.0 ${d} 0

ion N 0.76190476190

In [47]:
# Now we create the new lattice

In [53]:
[4.727486978767153   -2.363743489383575    0.000000000000000;
 -0.000000000000000    4.094123819672498    0.000000000000000;
 0.000000000000000    0.000000000000000   40.000000000000000]*superlattice_to_layer1_3x3

3×3 Matrix{Float64}:
 -11.8187     2.36374   0.0
   4.09412  -12.2824    0.0
   0.0        0.0      40.0

In [57]:
#Sanity check
rot_3x3(θ)*[4.727486978767153   -2.363743489383575    0.000000000000000;
 -0.000000000000000    4.094123819672498    0.000000000000000;
 0.000000000000000    0.000000000000000   40.000000000000000]*superlattice_to_layer2_3x3

3×3 Matrix{Float64}:
 -11.8187     2.36374   0.0
   4.09412  -12.2824    0.0
   0.0        0.0      40.0